### ISSUE TITLE
The Acrylic Glass plasmoid stopped working and no longer compiles after updating to Plasma 6.7 on my CachyOS install.

### ISSUE THREAD

**Issue by FAYZER77** [lestercorderomurillo/macos-tahoe-liquid-kde#9]
The Acrylic Glass plasmoid stopped working and no longer compiles after updating to Plasma 6.7 on my CachyOS install.  The first and most obvious issue is that it can't find header file wayland/blur.h.  Not sure what happened as I wouldn't think that it would just remove given it's a wayland file not a plasma file and I was able to build it prior to the plasma 6.7 update.  Obviously I totally get this is in development, just reporting the issue.  If there is a way I can help, please let me know.  Here is the relevant build output.

`Building acrylic glass
  ✗  Acrylic Glass: build failed
     ── make output (tail) ──
     [ 61%] Building CXX object src/CMakeFiles/liquidglass.dir/glassconfig.cpp.o
     [ 66%] Building CXX object src/kcm/CMakeFiles/kwin_liquidglass_config.dir/kwineffects_interface.cpp.o
     [ 71%] Building CXX object src/kcm/CMakeFiles/kwin_liquidglass_config.dir/kwin_liquidglass_config_autogen/mocs_compilation.cpp.o
     [ 76%] Building CXX object src/kcm/CMakeFiles/kwin_liquidglass_config.dir/glassconfig.cpp.o
     [ 80%] Building CXX object src/kcm/CMakeFiles/kwin_liquidglass_config.dir/config.cpp.o
     [ 85%] Linking CXX shared module kwin_liquidglass_config.so
     [ 90%] Built target kwin_liquidglass_config
     make: Leaving directory '/home/nerdinachair/Projects/source-code/remote/github/lestercorderomurillo/macos-tahoe-liquid-kde/build/kwin-effects/acrylic-glass'
     /home/nerdinachair/Projects/source-code/remote/github/lestercorderomurillo/macos-tahoe-liquid-kde/src/offline/kwin-effects/acrylic-glass/src/effect.cpp:22:10: fatal error: wayland/blur.h: No such file or directory
        22 | #include "wayland/blur.h"
           |          ^~~~~~~~~~~~~~~~
     compilation terminated.
     make[2]: *** [src/CMakeFiles/liquidglass.dir/build.make:131: src/CMakeFiles/liquidglass.dir/effect.cpp.o] Error 1
     make[2]: *** Waiting for unfinished jobs....
     In file included from /home/nerdinachair/Projects/source-code/remote/github/lestercorderomurillo/macos-tahoe-liquid-kde/src/offline/kwin-effects/acrylic-glass/src/main.cpp:7:
     /home/nerdinachair/Projects/source-code/remote/github/lestercorderomurillo/macos-tahoe-liquid-kde/src/offline/kwin-effects/acrylic-glass/src/effect.h:133:10: error: ‘void KWin::BlurEffect::prePaintScreen(KWin::ScreenPrePaintData&, std::chrono::milliseconds)’ marked ‘override’, but does not override
       133 |     void prePaintScreen(ScreenPrePaintData& data, std::chrono::milliseconds presentTime) override;
           |          ^~~~~~~~~~~~~~
     /home/nerdinachair/Projects/source-code/remote/github/lestercorderomurillo/macos-tahoe-liquid-kde/src/offline/kwin-effects/acrylic-glass/src/effect.h:138:10: error: ‘void KWin::BlurEffect::prePaintWindow(KWin::RenderView*, KWin::EffectWindow*, KWin::WindowPrePaintData&, std::chrono::milliseconds)’ marked ‘override’, but does not override
       138 |     void prePaintWindow(RenderView* view, EffectWindow* w, WindowPrePaintData& data, std::chrono::milliseconds presentTime) override;
           |          ^~~~~~~~~~~~~~
     make[2]: *** [src/CMakeFiles/liquidglass.dir/build.make:145: src/CMakeFiles/liquidglass.dir/main.cpp.o] Error 1
     make[1]: *** [CMakeFiles/Makefile2:199: src/CMakeFiles/liquidglass.dir/all] Error 2
     make[1]: *** Waiting for unfinished jobs....
     make: *** [Makefile:166: all] Error 2
     full log: /home/nerdinachair/Projects/source-code/remote/github/lestercorderomurillo/macos-tahoe-liquid-kde/build/kwin-effects/acrylic-glass/make-build.log

  ✗  build phase failed for: acrylic_glass
  All compiled components must build before any install step runs.
  Fix the build errors above (typically missing KF6/Qt6 dev packages) and re-run.
`

**Comment by lestercorderomurillo** [comment]
Working on a fix asap to support 6.7, thanks for reporting!!

**Comment by lestercorderomurillo** [comment]
Try again on the new version.

**Comment by FAYZER77** [comment]
Tested; fixed.  Man, mighty kind of you to fix this so quickly.  I don't expect that from any project.
